### ISSUE TITLE
Support building using pre-generated sources on windows-x86_64

### ISSUE THREAD

**Issue by ctz** [aws/aws-lc-rs#225]
### Problem:

At the minute building on windows-x86_64 gives this output (full log below):

```
(...)
  -- Go not found. Disabling some code generation and using pre-generated code in generated-src/
  -- Perl not found. Disabling some code generation and using pre-generated code in generated-src/
  -- The ASM_NASM compiler identification is NASM
  -- Found assembler: C:/Users/runneradmin/nasm/nasm.exe
  -- C:/Users/runneradmin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.9.0/aws-lc/generated-src/win-x86_64/crypto/ assembly files do not exist.
(...)

  CMake Error at aws-lc/crypto/CMakeLists.txt:286 (add_library):
    Cannot find source file:

      chacha/chacha-x86_64.asm

    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
    .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
    .f95 .f03 .hip .ispc

(...)
```

#### Relevant details

aws-lc-rs-sys 0.9.0 only contains generated-src for `win-aarch64`.

https://aws.github.io/aws-lc-rs/requirements/windows.html doesn't mention requirement for Perl or golang.

Build log:

```text
error: failed to run custom build command for `aws-lc-sys v0.9.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_TEST_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `D:\a\rustls\rustls\target\debug\build\aws-lc-sys-a3156c0dfbf5[74](https://github.com/rustls/rustls/actions/runs/5963826710/job/16177790487?pr=1414#step:6:75)53\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=use_bindgen_generated
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = Some("cmake")
  running: "cmake" "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\aws-lc-sys-0.9.0" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DBUILD_SHARED_LIBS=0" "-DBORINGSSL_PREFIX=aws_lc_0_9_0" "-DBORINGSSL_PREFIX_HEADERS=C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\aws-lc-sys-0.9.0\\generated-include" "-DBUILD_TESTING=OFF" "-DBUILD_LIBSSL=OFF" "-DDISABLE_PERL=ON" "-DDISABLE_GO=ON" "-DCMAKE_INSTALL_PREFIX=D:\\a\\rustls\\rustls\\target\\debug\\build\\aws-lc-sys-9cc6c10862390ca0\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug" "--no-warn-unused-cli"
  Not searching for unused variables given on the command line.
  -- The C compiler identification is MSVC 19.35.32217.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.35.32215/bin/HostX64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Go not found. Disabling some code generation and using pre-generated code in generated-src/
  -- Perl not found. Disabling some code generation and using pre-generated code in generated-src/
  -- The ASM_NASM compiler identification is NASM
  -- Found assembler: C:/Users/runneradmin/nasm/nasm.exe
  -- C:/Users/runneradmin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.9.0/aws-lc/generated-src/win-x86_64/crypto/ assembly files do not exist.
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - not found
  -- Found Threads: TRUE  
  -- Configuring done (122.2s)

  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:6 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Deprecation Warning at aws-lc/CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.5 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Error at aws-lc/crypto/CMakeLists.txt:286 (add_library):
    Cannot find source file:

      chacha/chacha-x86_64.asm

    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
    .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f[77](https://github.com/rustls/rustls/actions/runs/5963826710/job/16177790487?pr=1414#step:6:78) .f90
    .f95 .f03 .hip .ispc


  CMake Error at aws-lc/crypto/fipsmodule/CMakeLists.txt:499 (add_library):
    Cannot find source file:

      aesni-gcm-avx512.asm

    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
    .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
    .f95 .f03 .hip .ispc


  CMake Error at aws-lc/crypto/CMakeLists.txt:286 (add_library):
    No SOURCES given to target: crypto_objects


  CMake Error at aws-lc/crypto/CMakeLists.txt:542 (add_library):
    No SOURCES given to target: crypto
  Call Stack (most recent call first):
    aws-lc/crypto/CMakeLists.txt:633 (build_libcrypto)


  CMake Error at aws-lc/crypto/fipsmodule/CMakeLists.txt:499 (add_library):
    No SOURCES given to target: fipsmodule


  CMake Generate step failed.  Build files cannot be regenerated correctly.
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
     1: core::panicking::panic_fmt
               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
     2: cmake::find_exe::{{closure}}
     3: <cmake::Version as core::default::Default>::default
     4: cmake::Config::build
     5: build_script_main::prepare_cmake_build::{{closure}}
     6: build_script_main::prepare_cmake_build::{{closure}}
     7: core::ops::function::FnOnce::call_once
     8: <hashbrown::raw::RawTable<T,A> as core::ops::drop::Drop>::drop
     9: std::rt::lang_start::{{closure}}
    10: std::rt::lang_start_internal::closure$2
               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\rt.rs:148
    11: std::panicking::try::do_call
               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:500
    12: std::panicking::try
               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:464
    13: std::panic::catch_unwind
               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panic.rs:142
    14: std::rt::lang_start_internal
               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\rt.rs:148
    15: std::rt::lang_start
    16: main
    17: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:[78](https://github.com/rustls/rustls/actions/runs/5963826710/job/16177790487?pr=1414#step:6:79)
    18: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:2[88](https://github.com/rustls/rustls/actions/runs/5963826710/job/16177790487?pr=1414#step:6:89)
    19: BaseThreadInitThunk
    20: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Process completed with exit code 1.
```

https://github.com/rustls/rustls/actions/runs/5963826710/job/16177790487?pr=1414#step:6:74

**Comment by justsmth** [comment]
Go and Perl should not be needed for our normal (non-FIPS) build -- `generated-src` should have all of the required assembly files. We'll investigate why [`generated-src/win-x86/crypto/chacha/chacha-x86.asm`](https://github.com/aws/aws-lc/blob/main/generated-src/win-x86/crypto/chacha/chacha-x86.asm) wasn't found.

**Comment by justsmth** [comment]
I'm able to reproduce the bug:
```
> cargo build
   Compiling aws-lc-sys v0.10.0
error: failed to run custom build command for `aws-lc-sys v0.10.0`
...
  -- Go not found. Disabling some code generation and using pre-generated code in generated-src/
  -- Perl not found. Disabling some code generation and using pre-generated code in generated-src/
  -- C:/Users/Administrator/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.10.0/aws-lc/generated-src/win-x86_64/crypto/ assembly files do not exist.
  -- Configuring done (0.1s)

  --- stderr
  CMake Error at aws-lc/crypto/CMakeLists.txt:286 (add_library):
    Cannot find source file:

      chacha/chacha-x86_64.asm

    Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
    .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
...
```

Sorry about this. I hope to put out a patch revision to address this very soon.

**Comment by justsmth** [comment]
This PR should fix the bug: https://github.com/aws/aws-lc-rs/pull/227 I also added a `cargo publish --dry-run` check in our CI that should help prevent a regression on this.

I'll update this Issue when we publish our next revision.

**Comment by ctz** [comment]
> I'll update this Issue when we publish our next revision.

Thanks! Looking forward to trying this.

**Comment by justsmth** [comment]
Today we release a patch for [aws-lc-sys](https://crates.io/crates/aws-lc-sys/0.10.1) that should fix the build on Windows.  I verified that the build now succeeds on my Windows host:
```
PS C:\Users\Administrator\repos\aws-lc-rs-test> cargo run
...
   Compiling aws-lc-sys v0.10.1
   Compiling aws-lc-rs v1.3.0
   Compiling aws-lc-rs-test v0.1.0 (C:\Users\Administrator\repos\aws-lc-rs-test)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 09s
     Running `target\debug\aws-lc-rs-test.exe`
FIPS feature is not enabled!
c8ecec5c7c5ff5199184e8908c849a012c28338e78cc442117cb75ddd655ce52
```

**Comment by ctz** [comment]
Thanks -- that's working over here too!
