### ISSUE TITLE
Linux -> Mac cannot cross compile aws-lc-sys

### ISSUE THREAD

**Issue by brongan** [aws/aws-lc-rs#409]
### Problem:
On an x86_64 Linux box

```
cargo new repro
cd repro
cargo add aws-lc-rs
cargo b --target x86_64-apple-darwin
```

Fails with unknown flag errors.
```
  --- stderr
  thread 'main' panicked at /home/brong/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.15.0/builder/cc_builder.rs:225:9:
  COMPILER: "cc"ARGS: ["-O0", "-ffunction-sections", "-fdata-sections", "-fPIC", "-gdwarf-2", "-fno-omit-frame-pointer", "-m64", "-arch", "x86_64", "-mmacosx-version-min=10.7", "-Wall", "-Wextra", "/home/brong/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.15.0/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c", "-Wno-unused-parameter", "-o", "/home/brong/ws/repro/target/x86_64-apple-darwin/debug/build/aws-lc-sys-963977ec30e96b4e/out/memcmp_invalid_stripped_check"]EXECUTED: trueERROR: cc: error: unrecognized command-line option ‘-arch’
  cc: error: unrecognized command-line option ‘-mmacosx-version-min=10.7’
  OUTPUT: Failed to compile memcmp_invalid_stripped_check
 ```

#### Relevant details
aws-lc-rs 17

Linux 6.8.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 13 Apr 2024 14:44:53 +0000 x86_64 unknown

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.78.0-nightly (a4472498d 2024-02-15)

**Comment by thedjpetersen** [comment]
+1

**Comment by justsmth** [comment]
I can reproduce this on my Linux host.  I'm investigating now.

**Comment by justsmth** [comment]
The parameter appears to be added here: https://github.com/rust-lang/cc-rs/blob/994dc909dc54caa9eaa473b9807c171e1763d27e/src/lib.rs#L2659
```
...
        match arch {
            AppleArchSpec::Device(_) if is_mac => {
                cmd.args
                    .push(format!("-mmacosx-version-min={}", min_version).into());
            }
...
```

**Comment by justsmth** [comment]
Another related issue: https://github.com/rust-lang/cc-rs/issues/710

I'm not certain cross-compiling C/C++ code to MacOS from Linux via `cc-rs` is expect to work like this. I tried this same method and reproduced the failure with ring and openssl; they both generate the errors about these same flags:
```
  cargo:warning=cc: error: unrecognized debug output level ‘full’
  cargo:warning=cc: error: unrecognized command-line option ‘-arch’
  cargo:warning=cc: error: unrecognized command-line option ‘-mmacosx-version-min=10.7’
```

**Comment by brongan** [comment]
From https://rust-lang.github.io/rustup/cross-compilation.html

> Note that rustup target add only installs the Rust standard library for a given target. There are typically other tools necessary to cross-compile, particularly a linker. For example, to cross compile to Android the [Android NDK](https://developer.android.com/tools/sdk/ndk/index.html) must be installed. In the future, rustup will provide assistance installing the NDK components as well. See the [target section](https://doc.rust-lang.org/cargo/reference/config.html#target) of the cargo configuration for how to setup a linker to use for a certain target.

**Comment by justsmth** [comment]
Since cross-compiling from Linux to Mac is not something we currently plan to support. I'm  closing this issue.  Feel free to open another issue as a feature request if you'd like us to further investigate this as a cross-compilation option.

**Comment by vincent-thomas** [comment]
I'm getting similar error on m2 air:
```rust
arning: aws-lc-sys@0.31.0: Building with: CC
warning: aws-lc-sys@0.31.0: Symbol Prefix: Some("aws_lc_0_31_0")
warning: aws-lc-sys@0.31.0: Compilation of 'c11.c' succeeded - Ok(["/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out/out-c11/7dfda64fdf5a526c-c11.o"]).
warning: aws-lc-sys@0.31.0: Compilation of 'stdalign_check.c' succeeded - Ok(["/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out/out-stdalign_check/7dfda64fdf5a526c-stdalign_check.o"]).
warning: aws-lc-sys@0.31.0: Compilation of 'builtin_swap_check.c' succeeded - Ok(["/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out/out-builtin_swap_check/7dfda64fdf5a526c-builtin_swap_check.o"]).
error: failed to run custom build command for `aws-lc-sys v0.31.0`

Caused by:
  process didn't exit successfully: `/[path]/target/debug/build/aws-lc-sys-65906e152290e71e/build-script-main` (signal: 6, SIGABRT: process abort signal)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREGENERATING_BINDINGS_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREGENERATING_BINDINGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  cargo:rerun-if-env-changed=CFLAGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD
  cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREGENERATED_SRC_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREGENERATED_SRC
  cargo:rerun-if-env-changed=AWS_LC_SYS_EFFECTIVE_TARGET_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_EFFECTIVE_TARGET
  cargo:rustc-cfg=aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
  default_for Target: 'aarch64-apple-darwin'
  cargo:rerun-if-env-changed=CARGO_FEATURE_SSL
  cargo:warning=Building with: CC
  cargo:warning=Symbol Prefix: Some("aws_lc_0_31_0")
  default_for Target: 'aarch64-apple-darwin'
  cargo:rerun-if-env-changed=CARGO_FEATURE_SSL
  cargo:root=/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out
  default_for Target: 'aarch64-apple-darwin'
  OPT_LEVEL = Some(0)
  OUT_DIR = Some(/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out)
  TARGET = Some(aarch64-apple-darwin)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(true)
  CARGO_CFG_TARGET_FEATURE = Some(aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  CARGO_ENCODED_RUSTFLAGS = Some()
  OPT_LEVEL = Some(0)
  TARGET = Some(aarch64-apple-darwin)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(true)
  CARGO_CFG_TARGET_FEATURE = Some(aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  CARGO_ENCODED_RUSTFLAGS = Some()
  cargo:warning=Compilation of 'c11.c' succeeded - Ok(["/path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out/out-c11/7dfda64fdf5a526c-c11.o"]).
  cargo:rerun-if-env-changed=AWS_LC_SYS_CC_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_CC
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=AWS_LC_SYS_CXX_aarch64_apple_darwin
  cargo:rerun-if-env-changed=AWS_LC_SYS_CXX
  cargo:rerun-if-env-changed=CXX_aarch64_apple_darwin
  cargo:rerun-if-env-changed=CXX
  OUT_DIR = Some(/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  TARGET = Some(aarch64-apple-darwin)
  CARGO_CFG_TARGET_FEATURE = Some(aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  OUT_DIR = Some(/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out)
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  TARGET = Some(aarch64-apple-darwin)
  CARGO_CFG_TARGET_FEATURE = Some(aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  OPT_LEVEL = Some(0)
  TARGET = Some(aarch64-apple-darwin)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(true)
  CARGO_CFG_TARGET_FEATURE = Some(aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  CARGO_ENCODED_RUSTFLAGS = Some()
  cargo:warning=Compilation of 'stdalign_check.c' succeeded - Ok(["/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out/out-stdalign_check/7dfda64fdf5a526c-stdalign_check.o"]).
  OPT_LEVEL = Some(0)
  TARGET = Some(aarch64-apple-darwin)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(true)
  CARGO_CFG_TARGET_FEATURE = Some(aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  CARGO_ENCODED_RUSTFLAGS = Some()
  cargo:warning=Compilation of 'builtin_swap_check.c' succeeded - Ok(["/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out/out-builtin_swap_check/7dfda64fdf5a526c-builtin_swap_check.o"]).
  OPT_LEVEL = Some(0)
  OUT_DIR = Some(/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out)
  TARGET = Some(aarch64-apple-darwin)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(true)
  CARGO_CFG_TARGET_FEATURE = Some(aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  CARGO_ENCODED_RUSTFLAGS = Some()

  --- stderr

  thread 'main' panicked at /Users/vt/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.31.0/builder/cc_builder.rs:495:9:
  COMPILER: ccARGS: ["-O0", "-ffunction-sections", "-fdata-sections", "-fPIC", "-gdwarf-2", "-fno-omit-frame-pointer", "-arch", "arm64", "-mmacosx-version-min=15.5", "-Wall", "-Wextra", "/Users/vt/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.31.0/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c", "-Wno-unused-parameter", "-o", "/[path]/target/debug/build/aws-lc-sys-a8747770c980fa89/out/memcmp_invalid_stripped_check"]
EXECUTED: trueERROR: error: tool 'dsymutil' not found
  collect2: fatal error: /usr/bin/dsymutil returned 1 exit status
  compilation terminated.
  OUTPUT: Failed to compile memcmp_invalid_stripped_check

```

```sh
$ which dsymutil
/usr/bin/dsymutil
```

**Comment by justsmth** [comment]
Hello!  I'm parsing through the error message. 

```
EXECUTED: trueERROR: error: tool 'dsymutil' not found
```

This indicates that the compiler was invoked, and I believe the output produced by the compiler is `ERROR: error: tool 'dsymutil' not found`.

Do you see the same output when you execute the same command from the CLI?
```
cc -O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-2 -fno-omit-frame-pointer -arch arm64 -mmacosx-version-min=15.5 -Wall -Wextra /Users/vt/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.31.0/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c -Wno-unused-parameter -o memcmp_invalid_stripped_check
```

I also noticed that no compiler was specified: 
```
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
```

See the [comment above](https://github.com/aws/aws-lc-rs/issues/409#issuecomment-2078060429). There's likely some additional setup for the environment required so that cross-compilation will succeed.

**Comment by vincent-thomas** [comment]
```
$ cc -O0 -ffunction-sections -fdata-sections -fPIC -gdwarf-2 -fno-omit-frame-pointer -arch arm64 -mmacosx-version-min=15.5 -Wall -Wextra /Users/vt/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.31.0/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c -Wno-unused-parameter -o memcmp_invalid_stripped_check
error: tool 'dsymutil' not found
collect2: fatal error: /usr/bin/dsymutil returned 1 exit status
compilation terminated.
```

I might be missing something, but I'm not cross-compiling so the cross-compiling solution wouldn't apply to me?

I'm not able to compile anything that contains aws-lc-rs as a dependency currently. And the strange thing is that 'dsymutil' is in $PATH. Slightly lost about this issue, since the compiler thinks the tool is missing, when in fact it is available.

Thanks for any help.

**Comment by justsmth** [comment]
```
error: tool 'dsymutil' not found
```

This message seems misleading b/c on the next line it shows that it did find a `dsymutil` (located at `/usr/bin/dsymutil`) and when invoked it returned a 1 exit status.
```
collect2: fatal error: /usr/bin/dsymutil returned 1 exit status
```

I wonder whether your XCode installation might've gotten corrupted? Maybe try to set it up again using:
```
xcode-select --install
```

**Comment by vincent-thomas** [comment]
> I wonder whether your XCode installation might've gotten corrupted?

Yeah I tried that multiple times but without result. I ended up (for other reasons) getting another mac and now it's solved :).
