### ISSUE TITLE
FIPS fails to build with clang-18 on gcc 14

### ISSUE THREAD

**Issue by RonnyChan-okta** [aws/aws-lc-rs#607]
### Problem:

FIPS fails to build with clang-18, glibc 14

```
#19 74.21   libunwind not found. Disabling unwind tests.
#19 74.21   In file included from /usr/include/string.h:548,
#19 74.21                    from /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-fips-sys-0.12.14/aws-lc/crypto/asn1/a_bitstr.c:60:
#19 74.21   In function 'memcpy',
#19 74.21       inlined from 'OPENSSL_memcpy' at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-fips-sys-0.12.14/aws-lc/crypto/asn1/../internal.h:823:10,
#19 74.21       inlined from 'aws_lc_fips_0_12_14_i2c_ASN1_BIT_STRING' at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-fips-sys-0.12.14/aws-lc/crypto/asn1/a_bitstr.c:130:3:
#19 74.21   /usr/include/bits/string_fortified.h:29:10: error: '__builtin_memcpy' specified bound between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
#19 74.21      29 |   return __builtin___memcpy_chk (__dest, __src, __len,
#19 74.21         |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#19 74.21      30 |                                  __glibc_objsize0 (__dest));
#19 74.21         |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
#19 74.21   cc1: all warnings being treated as errors
#19 74.21   make[3]: *** [aws-lc/crypto/CMakeFiles/crypto_objects.dir/build.make:176: aws-lc/crypto/CMakeFiles/crypto_objects.dir/asn1/a_bitstr.c.o] Error 1
#19 74.21   make[2]: *** [CMakeFiles/Makefile2:280: aws-lc/crypto/CMakeFiles/crypto_objects.dir/all] Error 2
#19 74.21   make[1]: *** [Makefile:136: all] Error 2
#19 74.21   thread 'main' panicked at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.51/src/lib.rs:1100:5:
#19 74.21 
```

#### Relevant details
aws-lc-fips-sys-0.12.14

System information: for linux, below info can be collected by running `uname -srvmp`
 * CPU architecture: x86

We use the [chainguard/glibc-openssl-fips](
https://images.chainguard.dev/directory/image/glibc-openssl-fips/versions#/version/glibc-openssl-fips/ce2d1984a010471142503340d670612d63ffb9f6%2F09e8c31e3f546a8a%2Fd310aaf224f66e0b) docker image as our build image, with the following packages

```
apk add rust gcc go cmake openssl-dev clang-18 perl
```

uname output
```
Linux 6.6.31-linuxkit #1 SMP Thu May 23 08:36:57 UTC 2024 x86_64 unknown
```

Build log:
 * The log tells compiler and version.
```text
#18 13.83 cargo 1.82.0 (8f40fc59f 2024-08-21)
#18 13.85 rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball)

--

#19 74.21 The following warnings were emitted during compilation:
#19 74.21 
#19 74.21 warning: aws-lc-fips-sys@0.12.14: Building with: CMake
#19 74.21 warning: aws-lc-fips-sys@0.12.14: Symbol Prefix: Some("aws_lc_fips_0_12_14")
#19 74.21 warning: aws-lc-fips-sys@0.12.14: NOTICE: Build environment source paths might be visible in release binary.
#19 74.21 warning: aws-lc-fips-sys@0.12.14: Using flag: -ffile-prefix-map=/home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f=
#19 74.21 
#19 74.21 error: failed to run custom build command for `aws-lc-fips-sys v0.12.14`
#19 74.21 note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
#19 74.21 
#19 74.21 Caused by:
#19 74.21   process didn't exit successfully: `/home/build/engine/target/release/build/aws-lc-fips-sys-3d6fe3e1d4b13c3a/build-script-main` (exit status: 101)
#19 74.21   --- stdout
#19 74.21   cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_NO_PREFIX
#19 74.21   cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_PREGENERATING_BINDINGS
#19 74.21   cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_EXTERNAL_BINDGEN
#19 74.21   cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_NO_ASM
#19 74.21   cargo:rustc-cfg=x86_64_unknown_linux_gnu
#19 74.21   cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_STATIC
#19 74.21   cargo:warning=Building with: CMake
#19 74.21   cargo:warning=Symbol Prefix: Some("aws_lc_fips_0_12_14")
#19 74.21   cargo:rerun-if-env-changed=CMAKE
#19 74.21   cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_STATIC
#19 74.21   cargo:warning=NOTICE: Build environment source paths might be visible in release binary.
#19 74.21   OUT_DIR = Some(/home/build/target/release/build/aws-lc-fips-sys-a3f16bd5379b3a65/out)
#19 74.21   TARGET = Some(x86_64-unknown-linux-gnu)
#19 74.21   HOST = Some(x86_64-unknown-linux-gnu)
#19 74.21   cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
#19 74.21   CC_x86_64-unknown-linux-gnu = None
#19 74.21   cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
#19 74.21   CC_x86_64_unknown_linux_gnu = None
#19 74.21   cargo:rerun-if-env-changed=HOST_CC
#19 74.21   HOST_CC = None
#19 74.21   cargo:rerun-if-env-changed=CC
#19 74.21   CC = None
#19 74.21   cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
#19 74.21   RUSTC_WRAPPER = None
#19 74.21   OUT_DIR = Some(/home/build/target/release/build/aws-lc-fips-sys-a3f16bd5379b3a65/out)
#19 74.21   cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
#19 74.21   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
#19 74.21   CRATE_CC_NO_DEFAULTS = None
#19 74.21   TARGET = Some(x86_64-unknown-linux-gnu)
#19 74.21   CARGO_CFG_TARGET_FEATURE = Some(fxsr,sse,sse2)
#19 74.21   HOST = Some(x86_64-unknown-linux-gnu)
#19 74.21   cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
#19 74.21   CFLAGS_x86_64-unknown-linux-gnu = None
#19 74.21   cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
#19 74.21   CFLAGS_x86_64_unknown_linux_gnu = None
#19 74.21   cargo:rerun-if-env-changed=HOST_CFLAGS
#19 74.21   HOST_CFLAGS = None
#19 74.21   cargo:rerun-if-env-changed=CFLAGS
#19 74.21   CFLAGS = None
#19 74.21   cargo:warning=Using flag: -ffile-prefix-map=/home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f=
#19 74.21   cargo:rerun-if-env-changed=CMAKE_TOOLCHAIN_FILE
#19 74.21   cargo:rerun-if-env-changed=CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu
#19 74.21   CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
#19 74.21   CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
#19 74.21   HOST_CMAKE_TOOLCHAIN_FILE = None
#19 74.21   CMAKE_TOOLCHAIN_FILE = None
#19 74.21   CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
#19 74.21   CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
#19 74.21   HOST_CMAKE_GENERATOR = None
#19 74.21   CMAKE_GENERATOR = None
#19 74.21   CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
#19 74.21   CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
#19 74.21   HOST_CMAKE_PREFIX_PATH = None
#19 74.21   CMAKE_PREFIX_PATH = None
#19 74.21   CMAKE_x86_64-unknown-linux-gnu = None
#19 74.21   CMAKE_x86_64_unknown_linux_gnu = None
#19 74.21   HOST_CMAKE = None
#19 74.21   CMAKE = Some("cmake")
#19 74.21   running: cd "/home/build/target/release/build/aws-lc-fips-sys-a3f16bd5379b3a65/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-fips-sys-0.12.14" "-DBUILD_SHARED_LIBS=0" "-DCMAKE_BUILD_TYPE=release" "-DBORINGSSL_PREFIX=aws_lc_fips_0_12_14_" "-DBORINGSSL_PREFIX_HEADERS=/home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-fips-sys-0.12.14/generated-include" "-DBUILD_TESTING=OFF" "-DBUILD_LIBSSL=OFF" "-DFIPS=1" "-DCMAKE_INSTALL_PREFIX=/home/build/target/release/build/aws-lc-fips-sys-a3f16bd5379b3a65/out" "-DCMAKE_C_FLAGS= -ffile-prefix-map=/home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/local/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/local/bin/c++" "-DCMAKE_ASM_FLAGS= -ffile-prefix-map=/home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/local/bin/cc" "--no-warn-unused-cli"
#19 74.21   Not searching for unused variables given on the command line.
#19 74.21   -- The C compiler identification is GNU 14.2.0
#19 74.21   -- Detecting C compiler ABI info
#19 74.21   -- Detecting C compiler ABI info - done
#19 74.21   -- Check for working C compiler: /usr/local/bin/cc - skipped
#19 74.21   -- Detecting C compile features
#19 74.21   -- Detecting C compile features - done
#19 74.21   -- FIPS build mode configured
#19 74.21   -- FIPS entropy source method configured: Passive
#19 74.21   -- Found Perl: /usr/bin/perl (found version "5.40.0")
#19 74.21   -- Checking for module 'libunwind-generic'
#19 74.21   --   Package 'libunwind-generic' not found
#19 74.21   -- Run check_run file_to_test 'memcmp_invalid_stripped_check.c', flag_to_set 'MEMCMP_INVALID_STRIPPED', and compile_flags '-O3 -DNDEBUG'.
#19 74.21   -- stdalign_check.c probe is positive, enabling AWS_LC_STDALIGN_AVAILABLE
#19 74.21   -- builtin_swap_check.c probe is positive, enabling AWS_LC_BUILTIN_SWAP_SUPPORTED
#19 74.21   -- linux_u32.c probe is positive, enabling AWS_LC_URANDOM_U32
#19 74.21   -- The ASM compiler identification is GNU
#19 74.21   -- Found assembler: /usr/local/bin/cc
#19 74.21   -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
#19 74.21   -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
#19 74.21   -- Found Threads: TRUE
#19 74.21   -- Configuring done (20.6s)
#19 74.21   -- Generating done (0.1s)
#19 74.21   -- Build files have been written to: /home/build/target/release/build/aws-lc-fips-sys-a3f16bd5379b3a65/out/build
#19 74.21   running: cd "/home/build/target/release/build/aws-lc-fips-sys-a3f16bd5379b3a65/out/build" && MAKEFLAGS="-j --jobserver-fds=10,13 --jobserver-auth=10,13" "cmake" "--build" "." "--target" "install" "--config" "Release"
#19 74.21   make[1]: Entering directory '/home/build/target/release/build/aws-lc-fips-sys-a3f16bd5379b3a65/out/build'
#19 74.21   [  0%] Built target global_target
#19 74.21   [  0%] Built target boringssl_prefix_symbols
#19 74.21   [  0%] Generating test/trampoline-x86_64.S
#19 74.21   [  1%] Generating chacha/chacha-x86_64.S
#19 74.21   [  1%] Generating cipher_extra/aes128gcmsiv-x86_64.S
#19 74.21   [  1%] Generating cipher_extra/aesni-sha1-x86_64.S
#19 74.21   [  2%] Generating cipher_extra/aesni-sha256-x86_64.S
#19 74.21   [  2%] Generating cipher_extra/chacha20_poly1305_x86_64.S
#19 74.21   [  2%] Generating err_data.c
#19 74.21   [  2%] Building C object aws-lc/crypto/CMakeFiles/crypto_objects.dir/asn1/a_bitstr.c.o
#19 74.21   make[1]: Leaving directory '/home/build/target/release/build/aws-lc-fips-sys-a3f16bd5379b3a65/out/build'
#19 74.21 
#19 74.21   --- stderr
#19 74.21   CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
#19 74.21     Compatibility with CMake < 3.5 will be removed from a future version of
#19 74.21     CMake.
#19 74.21 
#19 74.21     Update the VERSION argument <min> value or use a ...<max> suffix to tell
#19 74.21     CMake that the project does not need compatibility with older versions.
#19 74.21 
#19 74.21 
#19 74.21   CMake Deprecation Warning at aws-lc/CMakeLists.txt:1 (cmake_minimum_required):
#19 74.21     Compatibility with CMake < 3.5 will be removed from a future version of
#19 74.21     CMake.
#19 74.21 
#19 74.21     Update the VERSION argument <min> value or use a ...<max> suffix to tell
#19 74.21     CMake that the project does not need compatibility with older versions.
#19 74.21 
#19 74.21 
#19 74.21   libunwind not found. Disabling unwind tests.
#19 74.21   In file included from /usr/include/string.h:548,
#19 74.21                    from /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-fips-sys-0.12.14/aws-lc/crypto/asn1/a_bitstr.c:60:
#19 74.21   In function 'memcpy',
#19 74.21       inlined from 'OPENSSL_memcpy' at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-fips-sys-0.12.14/aws-lc/crypto/asn1/../internal.h:823:10,
#19 74.21       inlined from 'aws_lc_fips_0_12_14_i2c_ASN1_BIT_STRING' at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-fips-sys-0.12.14/aws-lc/crypto/asn1/a_bitstr.c:130:3:
#19 74.21   /usr/include/bits/string_fortified.h:29:10: error: '__builtin_memcpy' specified bound between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
#19 74.21      29 |   return __builtin___memcpy_chk (__dest, __src, __len,
#19 74.21         |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#19 74.21      30 |                                  __glibc_objsize0 (__dest));
#19 74.21         |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
#19 74.21   cc1: all warnings being treated as errors
#19 74.21   make[3]: *** [aws-lc/crypto/CMakeFiles/crypto_objects.dir/build.make:176: aws-lc/crypto/CMakeFiles/crypto_objects.dir/asn1/a_bitstr.c.o] Error 1
#19 74.21   make[2]: *** [CMakeFiles/Makefile2:280: aws-lc/crypto/CMakeFiles/crypto_objects.dir/all] Error 2
#19 74.21   make[1]: *** [Makefile:136: all] Error 2
#19 74.21   thread 'main' panicked at /home/build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.51/src/lib.rs:1100:5:
#19 74.21 
#19 74.21   command did not execute successfully, got: exit status: 2
#19 74.21 
#19 74.21   build script failed, must exit now
#19 74.21   stack backtrace:
#19 74.21      0: rust_begin_unwind
#19 74.21      1: core::panicking::panic_fmt
#19 74.21      2: cmake::fail
#19 74.21      3: cmake::run
#19 74.21      4: cmake::Config::build
#19 74.21      5: build_script_main::cmake_builder::CmakeBuilder::build_rust_wrapper
#19 74.21      6: <build_script_main::cmake_builder::CmakeBuilder as build_script_main::Builder>::build
#19 74.21      7: build_script_main::main
#19 74.21      8: core::ops::function::FnOnce::call_once
#19 74.21   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
#19 74.21 warning: build failed, waiting for other jobs to finish...
#19 100.5 make: *** [Makefile:78: release] Error 101
...
```

**Comment by RonnyChan-okta** [comment]
Closing due to known FIPS build issue with GCC 14
