### ISSUE TITLE
aws-lc/crypto/err/err.c:186:17: error: implicit declaration of function ‘strdup’;

### ISSUE THREAD

**Issue by psumbera** [aws/aws-lc-rs#610]
### Problem:

Build on Solaris fails:

```
$ LIBCLANG_PATH=/usr/lib/64/libclang.so cargo build
..
   Compiling aws-lc-sys v0.23.0 (/builds/psumbera/aws-lc-rs/aws-lc-sys)
   Compiling aws-lc-fips-sys v0.12.14 (/builds/psumbera/aws-lc-rs/aws-lc-fips-sys)
The following warnings were emitted during compilation:

warning: aws-lc-fips-sys@0.12.14: Building with: CMake
warning: aws-lc-fips-sys@0.12.14: Symbol Prefix: Some("aws_lc_fips_0_12_14")
warning: aws-lc-fips-sys@0.12.14: Clang version: clang version 13.0.1
warning: aws-lc-fips-sys@0.12.14: Generating bindings - internal bindgen. Platform: x86_64-pc-solaris

error: failed to run custom build command for `aws-lc-fips-sys v0.12.14 (/builds/psumbera/aws-lc-rs/aws-lc-fips-sys)`

Caused by:
  process didn't exit successfully: `/builds/psumbera/aws-lc-rs/target/debug/build/aws-lc-fips-sys-b53e4ffe6fb1194b/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_PREGENERATING_BINDINGS
  cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_EXTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_NO_ASM
  cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_STATIC
  cargo:warning=Building with: CMake
  cargo:warning=Symbol Prefix: Some("aws_lc_fips_0_12_14")
  cargo:rerun-if-env-changed=CMAKE
  cargo:warning=Clang version: clang version 13.0.1
  cargo:warning=Generating bindings - internal bindgen. Platform: x86_64-pc-solaris
  cargo:rerun-if-env-changed=AWS_LC_FIPS_SYS_INCLUDES

  --- stderr
  /builds/psumbera/aws-lc-rs/aws-lc-fips-sys/include/rust_wrapper.h:9:10: fatal error: 'openssl/is_awslc.h' file not found
  thread 'main' panicked at aws-lc-fips-sys/builder/sys_bindgen.rs:105:10:
  Unable to generate bindings.: ClangDiagnostic("/builds/psumbera/aws-lc-rs/aws-lc-fips-sys/include/rust_wrapper.h:9:10: fatal error: 'openssl/is_awslc.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: aws-lc-sys@0.23.0: Building with: CMake
warning: aws-lc-sys@0.23.0: Symbol Prefix: Some("aws_lc_0_23_0")
warning: aws-lc-sys@0.23.0: CMAKE environment variable set: cmake
warning: aws-lc-sys@0.23.0: Clang version: clang version 13.0.1
warning: aws-lc-sys@0.23.0: Generating bindings - internal bindgen. Platform: x86_64-pc-solaris

error: failed to run custom build command for `aws-lc-sys v0.23.0 (/builds/psumbera/aws-lc-rs/aws-lc-sys)`

Caused by:
  process didn't exit successfully: `/builds/psumbera/aws-lc-rs/target/debug/build/aws-lc-sys-7a74670ccd16180a/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREGENERATING_BINDINGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD
  cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
  cargo:rerun-if-env-changed=CMAKE
  cargo:warning=Building with: CMake
  cargo:warning=Symbol Prefix: Some("aws_lc_0_23_0")
  cargo:rerun-if-env-changed=CMAKE
  cargo:warning=CMAKE environment variable set: cmake
  cargo:warning=Clang version: clang version 13.0.1
  cargo:warning=Generating bindings - internal bindgen. Platform: x86_64-pc-solaris
  cargo:rerun-if-env-changed=AWS_LC_SYS_INCLUDES

  --- stderr
  /builds/psumbera/aws-lc-rs/aws-lc-sys/include/rust_wrapper.h:9:10: fatal error: 'openssl/is_awslc.h' file not found
  thread 'main' panicked at aws-lc-sys/builder/sys_bindgen.rs:106:10:
  Unable to generate bindings.: ClangDiagnostic("/builds/psumbera/aws-lc-rs/aws-lc-sys/include/rust_wrapper.h:9:10: fatal error: 'openssl/is_awslc.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball)
SunOS 5.11 11.4.78.184.0 i86pc i386 i86pc non-virtualized

**Comment by psumbera** [comment]
For context why I'm trying this: https://github.com/rust-lang/rustup/issues/4094

**Comment by justsmth** [comment]
FYI -- I updated the title of the issue to indicate the problem that needs to be addressed.

**Comment by rami3l** [comment]
@psumbera you are right. The same problem is currently preventing a new Rustup release from happening for Illumos and NetBSD. FreeBSD seems to be the only outlier: https://github.com/rust-lang/rustup/pull/4105

**Comment by justsmth** [comment]
Oh.. I just looked through that output again.  There were a couple more errors.

* This first one might likewise be resolved by defining `_POSIX_C_SOURCE` prior to including "time.h".
```
aws-lc/crypto/fipsmodule/rand/urandom.c:129:3: error: implicit declaration of function ‘nanosleep’ [-Wimplicit-function-declaration] 
  129 |   nanosleep(&sleep_time, &sleep_time);
      |   ^~~~~~~~~
```

* The second one might be resolved by updating [the preprocessor guard](https://github.com/aws/aws-lc/blob/main/crypto/fipsmodule/rand/urandom.c#L352-L353) around the affected logic:
```
aws-lc/crypto/fipsmodule/rand/urandom.c:350:19: error: ‘RNDGETENTCNT’ undeclared (first use in this function)                                                            
  350 |     if (ioctl(fd, RNDGETENTCNT, &entropy_bits)) {
```

Note that the second one only affects a FIPS build. As our FIPS build has a lot of custom logic for MacOS/Linux/Windows, it's possible that our FIPS build will never succeed for a Solaris target. I would recommend not enabling the "fips" feature when building for Solaris.

**Comment by justsmth** [comment]
The Solaris man pages indicate that [nanosleep](https://docs.oracle.com/cd/E88353_01/html/E37843/nanosleep-3c.html) should be available. It's defined in "time.h", which that source file includes. I'm wondering if some of these compile errors are specific to the AWS-LC-FIPS v2.0 module. (We will soon to releasing the v3.0 module, which should resolve a lot of failures for the FIPS build.)

Would you try a non-FIPS build for Solaris to see whether you get the same errors? You can post any build errors that occur here if you'd like. Thanks!

**Comment by justinwsmith** [comment]
```
+    !(defined(OPENSSL_APPLE) || defined(OPENSSL_OPENBSD) || defined(OPENSSL_SOLARIS))  // On MacOS, iOS, OpenBSD and Solaris we don't use /dev/urandom.
```
For this, you also need to setup macros that define `OPENSSL_SOLARIS` when it detects that it's building for a Solaris system.  You can see a few examples here: https://github.com/aws/aws-lc/blob/main/include/openssl/target.h#L167-L177

**Comment by psumbera** [comment]
I have created following pull request: https://github.com/aws/aws-lc/pull/2035

This allows build on Solaris. With these changes FIPS modules isn't build.
